## Split Dataset
Split `all-data.csv` into three sets:
- **Train**: used to fit the models.
- **Val**: used to tune and compare models.
- **Test**: held out until the end for a final, unbiased evaluation.

In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/all-data.csv", header=None, names=['label', 'sentence'], encoding='latin-1')
df.head()

      label                                           sentence
0   neutral  According to Gran , the company has no plans t...
1   neutral  Technopolis plans to develop in stages an area...
2  negative  The international electronic industry company ...
3  positive  With the new production plant the company woul...
4  positive  According to the company 's updated strategy f...

In [4]:
print(df.shape)
print(df.describe())
print(df["label"].isna().sum())

(4846, 2)
          label                                           sentence
count      4846                                               4846
unique        3                                               4838
top     neutral  TELECOMWORLDWIRE-7 April 2006-TJ Group Plc sel...
freq       2879                                                  2
0

In [11]:
print("Counts: ")
print(df['label'].value_counts(), "\n")
print("Proportion")
share_label = df['label'].value_counts(normalize=True).round(3)
print(share_label.multiply(100))

Counts:
label
neutral     2879
positive    1363
negative     604
Name: count, dtype: int64

Proportion
label
neutral     59.4
positive    28.1
negative    12.5
Name: proportion, dtype: float64

For an imbalanced dataset like this, we use macro F1 as our main metric, as it exposes a model that ignores negatives.

In [ ]:
n_before = len(df)
df = df.drop_duplicates()
print("Found exact duplicates: ", n_before - len(df))

Found exact duplicates:  6

In [21]:
duplicate = df[df.duplicated("sentence", keep=False)]
print(display(duplicate))
df = df.drop_duplicates("sentence", keep=False)
print(len(df))

Empty DataFrame
Columns: [label, sentence]
Index: []

None
4836

In [22]:
train_val, test = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

print(len(train_val))

3868

In [23]:
train, val = train_test_split(train_val, test_size=0.25, random_state=42, stratify=train_val['label'])

In [24]:
print("Train: ", len(train))
print("Val: ", len(val))
print("Test: ", len(test))
print("Total equal: ", (len(train) + len(val) + len(test)) == len(df))

Train:  2901
Val:  967
Test:  968
Total equal:  True

### Save to file

In [25]:
train.to_csv("../data/train.csv", index=False)
val.to_csv("../data/val.csv", index=False)
test.to_csv("../data/test.csv", index=False)